version: "3"
services:
  mysql:
    image: mysql:8.0
    restart: always
    volumes:
      - mysql-cnf:/etc/mysql
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: randomSQLPWD1234
    networks:
      - aries_net

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: randomMongoPWD1234
    volumes:
      - mongo-data:/data/db
    networks:
      - aries_net

  messenger:
    image: aries/messenger
    restart: always
    ports:
      - 4000:4000
    networks:
      - aries_net

  server:
    image: aries/server
    restart: always
    ports:
      - 3000:3000
    networks:
      - aries_net

volumes:
  mysql-cnf:
  mysql-data:
  mongo-data:

networks:
  aries_net: